

dist: bionic

services:
  - docker

language: cpp

env:
  matrix:
    - SETUPSCRIPT=/cvmfs/sw.hsf.org/key4hep/setup.sh; STANDARD=17; BUILD_DDG4EDM4HEP=ON; BUILD_DELPHESEDM4HEP=ON; PODIO_FROM=STACK; STACK=KEY4HEPNIGHTLY;
    - SETUPSCRIPT=/cvmfs/sw.hsf.org/key4hep/setup.sh; STANDARD=17; BUILD_DDG4EDM4HEP=ON; BUILD_DELPHESEDM4HEP=ON; PODIO_FROM=BUILD_HEAD_ONTHEFLY; STACK=KEY4HEPNIGHTLY;
    - SETUPSCRIPT=/cvmfs/sft.cern.ch/lcg/views/dev3/latest/x86_64-centos7-gcc8-opt/setup.sh; STANDARD=17; BUILD_DDG4EDM4HEP=ON; BUILD_DELPHESEDM4HEP=ON; PODIO_FROM=BUILD_HEAD_ONTHEFLY; STACK=KEY4HEPNIGHTLY;
    - SETUPSCRIPT=/cvmfs/sft.cern.ch/lcg/views/dev3/latest/x86_64-centos7-clang8-opt/setup.sh; STANDARD=17; BUILD_DDG4EDM4HEP=ON; BUILD_DELPHESEDM4HEP=ON; PODIO_FROM=BUILD_HEAD_ONTHEFLY; STACK=KEY4HEPNIGHTLY;

matrix:
  allow_failures:
  - env: SETUPSCRIPT=/cvmfs/sw.hsf.org/key4hep/setup.sh; STANDARD=17; BUILD_DDG4EDM4HEP=ON; BUILD_DELPHESEDM4HEP=ON; PODIO_FROM=STACK; STACK=KEY4HEPNIGHTLY;
  - env: SETUPSCRIPT=/cvmfs/sft.cern.ch/lcg/views/dev3/latest/x86_64-centos7-clang8-opt/setup.sh; STANDARD=17; BUILD_DDG4EDM4HEP=ON; BUILD_DELPHESEDM4HEP=ON; PODIO_FROM=BUILD_HEAD_ONTHEFLY; STACK=KEY4HEPNIGHTLY;
  - env: SETUPSCRIPT=/cvmfs/sft.cern.ch/lcg/views/dev3/latest/x86_64-centos7-gcc8-opt/setup.sh; STANDARD=17; BUILD_DDG4EDM4HEP=ON; BUILD_DELPHESEDM4HEP=ON; PODIO_FROM=BUILD_HEAD_ONTHEFLY; STACK=KEY4HEPNIGHTLY;

before_install:
  - wget --no-check-certificate https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
  - sudo dpkg -i cvmfs-release-latest_all.deb
  - sudo apt-get update
  - sudo apt-get install cvmfs cvmfs-config-default
  - rm -f cvmfs-release-latest_all.deb
  - sudo mkdir -p /etc/cvmfs
  - echo "CVMFS_QUOTA_LIMIT='32140'"                                | sudo tee     /etc/cvmfs/default.local > /dev/null
  - echo "CVMFS_HTTP_PROXY=DIRECT"                                  | sudo tee -a  /etc/cvmfs/default.local > /dev/null
  - echo "CVMFS_CACHE_BASE='/var/lib/cvmfs'"                        | sudo tee -a  /etc/cvmfs/default.local > /dev/null
  - echo "CVMFS_FORCE_SIGNING='yes'"                                | sudo tee -a  /etc/cvmfs/default.local > /dev/null
  - echo "CVMFS_REPOSITORIES='sft.cern.ch,sw.hsf.org,sw-nightlies.hsf.org,sft-nightlies.cern.ch,geant4.cern.ch'"    | sudo tee -a  /etc/cvmfs/default.local > /dev/null
  - echo "CVMFS_SEND_INFO_HEADER=no"                                | sudo tee -a  /etc/cvmfs/default.local > /dev/null
  - cat /etc/cvmfs/default.local
  - # change wrt dd4hep setup: don't manually mount cvmfs folders
  - #sudo /etc/init.d/autofs stop
  - sudo cvmfs_config setup
  - sudo cvmfs_config probe
  - sudo mkdir -p /cvmfs/sft.cern.ch
  - sudo mkdir -p /cvmfs/sft-nightlies.cern.ch
  - sudo mkdir -p /cvmfs/geant4.cern.ch
  - sudo mkdir -p /cvmfs/sw-nightlies.hsf.org
  - sudo mkdir -p /cvmfs/sw.hsf.org
  - ls /cvmfs/sft.cern.ch
  - ls /cvmfs/geant4.cern.ch
  - ls /cvmfs/sw-nightlies.hsf.org
  - ls /cvmfs/sw.hsf.org
  - export CVMFS_REPOS="-v /cvmfs/sft.cern.ch:/cvmfs/sft.cern.ch"
  - export CVMFS_REPOS="${CVMFS_REPOS} -v /cvmfs/sw-nightlies.hsf.org:/cvmfs/sw-nightlies.hsf.org"
  - export CVMFS_REPOS="${CVMFS_REPOS} -v /cvmfs/sw.hsf.org:/cvmfs/sw.hsf.org"
  - export CVMFS_REPOS="${CVMFS_REPOS} -v /cvmfs/geant4.cern.ch:/cvmfs/geant4.cern.ch"


# command to install dependencies
install:
  - shopt -s extglob dotglob
  - mkdir package
  - mv !(package) package
  - shopt -u dotglob
  - export PKGDIR=${PWD}/package

# command to run tests
script:
  - docker run -ti --name CI_CONTAINER -v $PKGDIR:/workspace  -e SETUPSCRIPT=${SETUPSCRIPT}  -e BUILD_DDG4EDM4HEP=${BUILD_DDG4EDM4HEP} -e BUILD_DELPHESEDM4HEP=${BUILD_DELPHESEDM4HEP} -e STANDARD=${STANDARD} -v /cvmfs:/cvmfs:shared -d clicdp/cc7-lcg bash 
  - if [[ "$PODIO_FROM" == "STACK" ]]; 
    then docker exec -ti CI_CONTAINER  /bin/bash -c "cd /workspace; pwd; ls; source ${SETUPSCRIPT}; source ./.edm4hep-ci.d/compile_and_test.sh";
    elif [[ "$PODIO_FROM" == "BUILD_HEAD_ONTHEFLY" ]];
    then docker exec -ti CI_CONTAINER  /bin/bash -c "cd /workspace; pwd; ls; source ${SETUPSCRIPT}; source ./.edm4hep-ci.d/compile_and_test_with_podio.sh; source ./.edm4hep-ci.d/compile_and_test.sh;";
    fi



after_success:
  # Generate the docs only if master, the travis_build_docs is true and we can use secure variables
  - >-
    if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_PULL_REQUEST" = "false" ]] ; then

       cd ${PKGDIR}; docker exec -ti CI_CONTAINER  /bin/bash -c "cd /workspace; source init.sh; cd build; ninja  doc" && ./.edm4hep-ci.d/generateDocumentation.sh || travis_terminate 1
    fi

# Don't send e-mail notifications
notifications:
  email: false
