sudo: required
dist: trusty

services:
  - docker

language: cpp

env:
  matrix:
    - COMPILER=gcc

before_install:
  - docker pull gitlab-registry.cern.ch/lhcb-core/lbdocker/centos7-build:latest


# command to run tests
script: 
  - docker run -it -v ${PWD}:/workspace -w /workspace  --privileged -e LHCB_ENV_MODE=none -u 0:0 -e USER=root -e GROUP=root -e CMTCONFIG=x86_64-centos7-gcc8-opt  gitlab-registry.cern.ch/lhcb-core/lbdocker/centos7-build:latest bash -c "pwd; ls ;./.edm4hep-ci.d/compile_and_test_with_podio.sh"

# Don't send e-mail notifications
notifications:
  email: false

