sudo: required
dist: trusty

services:
  - docker

language: cpp

env:
  matrix:
    - COMPILER=gcc
    - COMPILER=llvm

before_install:
  - wget --no-check-certificate https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
  - sudo dpkg -i cvmfs-release-latest_all.deb
  - sudo apt-get update
  - sudo apt-get install cvmfs cvmfs-config-default
  - rm -f cvmfs-release-latest_all.deb
  - wget --no-check-certificate https://lcd-data.web.cern.ch/lcd-data/CernVM/default.local
  - sudo mkdir -p /etc/cvmfs
  - sudo mv default.local /etc/cvmfs/default.local
  - sudo /etc/init.d/autofs stop
  - sudo cvmfs_config setup
  - sudo mkdir -p /cvmfs/sft.cern.ch
  - sudo mount -t cvmfs sft.cern.ch /cvmfs/sft.cern.ch
  - ls /cvmfs/sft.cern.ch

# command to install dependencies
install:
  - shopt -s extglob dotglob
  - mkdir Package
  - mv !(Package) Package
  - shopt -u dotglob
  - export PKGDIR=${PWD}/Package

# command to run tests
script:
  - docker run -ti --name CI_container -v $PKGDIR:/edm4hep -e COMPILER_TYPE=$COMPILER -v /cvmfs/sft.cern.ch:/cvmfs/sft.cern.ch -d cern/cc7-base /bin/bash
  - docker exec -ti CI_container /bin/bash -c "yum install which make glibc-devel -y"
  - docker exec -ti CI_container /bin/bash -c ""

# Don't send e-mail notifications
notifications:
  email: false

